// Learn more about Tauri commands at https://tauri.app/develop/calling-rust/
mod sub_apps;

#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(tauri::generate_handler![
            greet,
            sub_apps::project_manager::create_project,
            sub_apps::project_manager::get_projects,
            sub_apps::project_manager::update_project,
            sub_apps::project_manager::delete_project,
            sub_apps::project_manager::create_sprint,
            sub_apps::project_manager::get_sprints,
            sub_apps::project_manager::update_sprint,
            sub_apps::project_manager::delete_sprint,
            sub_apps::project_manager::create_issue,
            sub_apps::project_manager::get_issues,
            sub_apps::project_manager::update_issue,
            sub_apps::project_manager::delete_issue,
            sub_apps::project_manager::create_comment,
            sub_apps::project_manager::get_comments,
            sub_apps::project_manager::delete_comment,
            sub_apps::project_manager::create_label,
            sub_apps::project_manager::get_labels,
            sub_apps::project_manager::delete_label,
            sub_apps::project_manager::toggle_issue_label,
            sub_apps::project_manager::get_issue_labels,
            sub_apps::project_manager::create_issue_link,
            sub_apps::project_manager::get_issue_links,
            sub_apps::project_manager::delete_issue_link,
            sub_apps::project_manager::create_worklog,
            sub_apps::project_manager::get_worklogs,

            // Advanced Project Manager
            sub_apps::project_manager::create_version,
            sub_apps::project_manager::get_versions,
            sub_apps::project_manager::update_version,
            sub_apps::project_manager::delete_version,
            sub_apps::project_manager::create_issue_history,
            sub_apps::project_manager::get_issue_history,
            sub_apps::project_manager::get_workflow_statuses,
            sub_apps::project_manager::create_workflow_status,
            sub_apps::project_manager::delete_workflow_status,
            sub_apps::project_manager::create_saved_filter,
            sub_apps::project_manager::get_saved_filters,
            sub_apps::project_manager::delete_saved_filter,
            sub_apps::project_manager::jql_search,
            sub_apps::project_manager::upload_attachment,
            sub_apps::project_manager::read_attachment,
            sub_apps::project_manager::get_attachments,
            sub_apps::project_manager::delete_attachment,
            sub_apps::project_manager::create_custom_field,
            sub_apps::project_manager::get_custom_fields,
            sub_apps::project_manager::get_issue_custom_fields,
            sub_apps::project_manager::set_custom_field_value,
            sub_apps::project_manager::create_automation_rule,
            sub_apps::project_manager::get_automation_rules,
            sub_apps::project_manager::delete_automation_rule,

            sub_apps::photo_editor::photo_export_file,

            sub_apps::finance_manager::get_transactions,
            sub_apps::finance_manager::create_transaction,
            sub_apps::finance_manager::delete_transaction,
            sub_apps::finance_manager::create_account,
            sub_apps::finance_manager::get_accounts,
            sub_apps::finance_manager::create_budget,
            sub_apps::finance_manager::get_budgets,
            sub_apps::finance_manager::create_goal,
            sub_apps::finance_manager::get_goals,
            sub_apps::finance_manager::create_subscription,
            sub_apps::finance_manager::get_subscriptions,
            sub_apps::finance_manager::create_debt,
            sub_apps::finance_manager::get_debts,
            sub_apps::finance_manager::create_invoice,
            sub_apps::finance_manager::get_invoices,
            sub_apps::finance_manager::create_chart_of_account,
            sub_apps::finance_manager::get_chart_of_accounts,
            sub_apps::finance_manager::create_journal_entry,
            sub_apps::finance_manager::get_journal_entries,
            sub_apps::finance_manager::create_vendor_bill,
            sub_apps::finance_manager::get_vendor_bills,
            sub_apps::finance_manager::create_fixed_asset,
            sub_apps::finance_manager::get_fixed_assets,
            sub_apps::finance_manager::create_purchase_order,
            sub_apps::finance_manager::get_purchase_orders,
            sub_apps::finance_manager::create_inventory_item,
            sub_apps::finance_manager::get_inventory_items,
            sub_apps::finance_manager::create_tax_code,
            sub_apps::finance_manager::get_tax_codes,
            sub_apps::finance_manager::create_audit_log,
            sub_apps::finance_manager::get_audit_logs,
            sub_apps::finance_manager::create_period_close,
            sub_apps::finance_manager::get_period_closes,
            sub_apps::finance_manager::create_exchange_rate,
            sub_apps::finance_manager::get_exchange_rates,
            sub_apps::finance_manager::create_ar_recurring_billing,
            sub_apps::finance_manager::get_ar_recurring_billing,
            sub_apps::finance_manager::create_ar_dunning_campaign,
            sub_apps::finance_manager::get_ar_dunning_campaigns,
            sub_apps::finance_manager::create_ar_revrec_schedule,
            sub_apps::finance_manager::get_ar_revrec_schedules,

            // Notes Taking
            sub_apps::notes_taking::notes_create_note,
            sub_apps::notes_taking::notes_get_notes,
            sub_apps::notes_taking::notes_update_note,
            sub_apps::notes_taking::notes_delete_note,
            sub_apps::notes_taking::notes_search_notes,
            sub_apps::notes_taking::notes_create_notebook,
            sub_apps::notes_taking::notes_get_notebooks,
            sub_apps::notes_taking::notes_update_notebook,
            sub_apps::notes_taking::notes_delete_notebook,
            sub_apps::notes_taking::notes_create_tag,
            sub_apps::notes_taking::notes_get_tags,
            sub_apps::notes_taking::notes_update_tag,
            sub_apps::notes_taking::notes_delete_tag,
            sub_apps::notes_taking::notes_add_tag_to_note,
            sub_apps::notes_taking::notes_remove_tag_from_note,
            sub_apps::notes_taking::notes_get_note_tags,
            sub_apps::notes_taking::notes_create_link,
            sub_apps::notes_taking::notes_get_links,
            sub_apps::notes_taking::notes_delete_link,
            sub_apps::notes_taking::notes_get_backlinks,
            sub_apps::notes_taking::notes_get_all_links,
            sub_apps::notes_taking::notes_create_version,
            sub_apps::notes_taking::notes_get_versions,
            sub_apps::notes_taking::notes_create_template,
            sub_apps::notes_taking::notes_get_templates,
            sub_apps::notes_taking::notes_delete_template,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
